stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build:
  stage: build
  tags:
    - controller
  script:
    - cd /root/projects/nyt
    - git pull
    - npm install


deploy:
  stage: deploy
  tags:
    - controller
  script:
    - echo Test123 | sudo -S pm2 restart 0

